drop table if exists appointment cascade;
drop table if exists doctor cascade;
drop table if exists doctor_speciality cascade;
drop table if exists employee cascade;
drop table if exists exam cascade;
drop table if exists patient cascade;
drop table if exists pendingsdp cascade;
drop table if exists prontidao cascade;
drop table if exists scheduling cascade;
drop table if exists users cascade;

create table appointment (
                             date date,
                             fim time(6),
                             inicio time(6),
                             notified boolean not null,
                             fk_doctor bigint,
                             fk_patient bigint,
                             id bigint generated by default as identity,
                             description TEXT,
                             speciality enum ('CARDIOLOGISTA','CLINICOGERAL','DERMATOLOGISTA','ENDCRINOLOGISTA','GASTROENTEROLOGISTA','GINECOLOGISTA','NEUROLOGISTA','OFTALMOLOGISTA','ONCOLOGISTA','ORTOPEDISTA','OTORRINOLARINGOLOGISTA','PEDIATRA','PROCTOLOGISTA','PSIQUIATRA','UROLOGISTA'),
                             primary key (id)
);

create table doctor (
                        id bigint not null,
                        crm varchar(255),
                        primary key (id)
);

create table doctor_speciality (
                                   doctor_id bigint not null,
                                   speciality enum ('CARDIOLOGISTA','CLINICOGERAL','DERMATOLOGISTA','ENDCRINOLOGISTA','GASTROENTEROLOGISTA','GINECOLOGISTA','NEUROLOGISTA','OFTALMOLOGISTA','ONCOLOGISTA','ORTOPEDISTA','OTORRINOLARINGOLOGISTA','PEDIATRA','PROCTOLOGISTA','PSIQUIATRA','UROLOGISTA')
);

create table employee (
                          id bigint not null,
                          office enum ('MANAGER','RECEPTIONIST'),
                          primary key (id)
);

create table exam (
                      date timestamp(6),
                      fk_appointment bigint,
                      id bigint generated by default as identity,
                      description TEXT,
                      primary key (id)
);

create table patient (
                         id bigint not null,
                         primary key (id)
);

create table pendingsdp (
                            id bigint generated by default as identity,
                            doctor_email varchar(255),
                            message varchar(255),
                            primary key (id)
);

create table prontidao (
                           data date not null,
                           em_consulta boolean not null,
                           fim time(6) not null,
                           inicio time(6) not null,
                           doctor_id bigint,
                           id bigint generated by default as identity,
                           primary key (id)
);

create table scheduling (
                            date date not null,
                            end_time time(6) not null,
                            home_time time(6) not null,
                            vagas integer,
                            doctor_id bigint,
                            id bigint generated by default as identity,
                            speciality_type enum ('CARDIOLOGISTA','CLINICOGERAL','DERMATOLOGISTA','ENDCRINOLOGISTA','GASTROENTEROLOGISTA','GINECOLOGISTA','NEUROLOGISTA','OFTALMOLOGISTA','ONCOLOGISTA','ORTOPEDISTA','OTORRINOLARINGOLOGISTA','PEDIATRA','PROCTOLOGISTA','PSIQUIATRA','UROLOGISTA'),
                            tipo_agendamento enum ('CONSULTA','CONSULTA_ONLINE','PRONTIDAO'),
                            primary key (id)
);

create table users (
                       birth_date date,
                       id bigint generated by default as identity,
                       cpf varchar(255) unique,
                       email varchar(255) unique,
                       name varchar(255),
                       password varchar(255),
                       acess_level enum ('ATTENDANT','DOCTOR','MANAGER','PATIENT'),
                       primary key (id)
);

alter table if exists appointment add constraint FK3cwmip1cnkrnfqv10cauct53h foreign key (fk_doctor) references doctor on delete cascade;
alter table if exists appointment add constraint FKiev1kvcythsqtwxiyiiyatv0x foreign key (fk_patient) references patient on delete cascade;
alter table if exists doctor add constraint FKfov306el30u8xq4c5xa7r31ip foreign key (id) references users;
alter table if exists doctor_speciality add constraint FKcx4a5pih7migmeb7x6ht9p9au foreign key (doctor_id) references doctor;
alter table if exists employee add constraint FK4do49krwrc71hlqh6deig5oa6 foreign key (id) references users;
alter table if exists exam add constraint FKifr225efjy36uf2g5nrdtjjb foreign key (fk_appointment) references appointment;
alter table if exists patient add constraint FKf0or75ex3abs31ottuqg8s301 foreign key (id) references users;
alter table if exists prontidao add constraint FK82qfslki3mklne4g7gx24w6q6 foreign key (doctor_id) references doctor;
alter table if exists scheduling add constraint FKbhs2rtrboq1iu1u3thlepud3k foreign key (doctor_id) references doctor;
